language: node_js
dist: trusty
sudo: false
node_js:
  - "iojs"
  - "7"
  - "6"
  - "5"
  - "4"
  - "0.12"
  - "0.11"
  - "0.10"

matrix:
  allow_failures:
    - node_js: "iojs"
    - node_js: "7"
    - node_js: "6"
    - node_js: "5"

script: make test
